[package]
name = "mnsv2"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
clap = { version = "4.3.19", features = ["derive"] }
home = "0.5.5"
lettre = "0.10.4"
once_cell = "1.18.0"
serde = { version = "1.0.171", features = ["derive"] }
toml = "0.7.5"
